AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DynamoDBTable:
    Type: String
    Description: DynamoDB table for SSM parameters
    Default: uredu-academy-final-table

Resources:
  UreduAcademyFinalDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref DynamoDBTable
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1