AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SecretsManagerName:
    Type: String

Resources:
  SecretsManager:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref SecretsManagerName
      Description: "Secret for uredu-academy-final-secretsmanager"